### ISSUE TITLE
Timer will be suppressed by GC

### ISSUE THREAD

**Issue by MortalKim** [Kyome22/ActivityKit#2]
I'm new to swift.

In MyApp.swift, I have code like this:

```
@main
struct MyApp: App {

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }

    init(){
            let observer = ActivityObserver()
            observer.updatedStatisticsHandler = { observer in
                Swift.print(observer.statistics)
            }
            observer.start(interval: 3)
    }
}
```

And it not working, by debuging, Timer never worked.

If I debug my App, and watch timer's memory, Then Timer works.

So I think it is a GC problem, Any ideas?

BTW, I have to write a TImer by myself, and it works now.

System: Mac os 14
Xcode: 14
Model: Mac mini m1

**Comment by Kyome22** [comment]
@MortalKim 
Thank you for trying to use ActivityKit!

The place where you are writing `let observer = ActivityObserver()` is not good.
If you declare `observer` in the init scope, it will be destroyed after initialization; you need to keep the observer instance.

The following code worked.

```swift
@main
struct MyApp: App {
    let observer = ActivityObserver()

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }

    init(){
            observer.updatedStatisticsHandler = { observer in
                Swift.print(observer.statistics)
            }
            observer.start(interval: 3)
    }
}
```

In addition, it is more reliable to write it in AppDelegate.

**Comment by MortalKim** [comment]
> 

@Kyome22 Thanks for your help. I tried this code and it works. I'm silly 😮‍💨.

I'm new for swift but I'm not new for develop, and I don't find where problem is. 😂I'm not even try this.

BTW, Activity is works fine to get system info.
